//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetAptekaMurzik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptInvoice
    {
        public int id_receiptInvoice { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<decimal> PriceInvoice { get; set; }
        public int id_product { get; set; }
        public int id_provider { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
